spring.application.name=ecommerce-gamer-api
spring.jpa.hibernate.ddl-auto=update

## CONFIG LOCAL
#api.security.token.secret=123

## DB LOCAL
#spring.datasource.username=root
#spring.datasource.password=123
#spring.datasource.url=jdbc:mysql://localhost:3306/table_ecommerce

## DB LOCAL - DOCKER
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jackson.property-naming-strategy=SNAKE_CASE


