name: Deploy - CI/CD Pipeline para AWS EC2

on:
  push:
    branches: [ "dev_env" ]

jobs:
  deploy:
    name: Deploy na AWS EC2 via SSM
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pega o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Step 2: Configura as credenciais da AWS
      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      # Step 3: Envia o comando de deploy para a EC2
      - name: Enviar comando de deploy para a EC2 via SSM Run Command
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy da aplicação" \
            --parameters 'commands=[
              "cd /home/ec2-user/ecommerce-gamer-api",
              "git pull",
              echo "SPRING_DATASOURCE_URL=${{ secrets.RDS_URL }}
              SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USERNAME }}
              SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }}
              API_SECURITY_TOKEN_SECRET=${{ secrets.JWT_SECRET }}" > .env
              "sudo docker-compose -f docker-compose.prod.yml up --build -d --force-recreate"
            ]'