name: CI/CD Pipeline para Oracle Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy na Oracle Cloud VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ecommerce-gamer-api
            git pull

            # Cria o .env com os segredos do RDS
            echo "SPRING_DATASOURCE_URL=${{ secrets.RDS_URL }}" > .env
            echo "SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USERNAME }}" >> .env
            echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> .env
            echo "API_SECURITY_TOKEN_SECRET=${{ secrets.JWT_SECRET }}" >> .env

            # USA O ARQUIVO DE PRODUÇÃO E FORÇA A RECRIAÇÃO DO CONTAINER 'APP'
            sudo docker-compose -f docker-compose.prod.yml up --build -d --force-recreate